export const dataMock = {
  drinks: [
    {
      idDrink: '11320',
      strDrink: 'Dragonfly',
      strDrinkAlternate: null,
      strDrinkES: null,
      strDrinkDE: null,
      strDrinkFR: null,
      'strDrinkZH-HANS': null,
      'strDrinkZH-HANT': null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions:
        'In a highball glass almost filled with ice cubes, combine the gin and ginger ale. Stir well. Garnish with the lime wedge.',
      strInstructionsES: null,
      strInstructionsDE:
        'In einem Highball-Glas, das fast mit Eiswürfeln gefüllt ist, den Gin mit dem Ginger Ale vermengen. Gut umrühren. Mit dem Limettenkeil garnieren.',
      strInstructionsFR: null,
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/uc63bh1582483589.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Ginger ale',
      strIngredient3: 'Lime',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '4 oz ',
      strMeasure3: '1 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-02 22:51:40',
    },
  ],
};
